config/routes.rb
Rails.application.routes.draw do
  resources :orders
  root 'orders#index'
  get '/print', to: 'orders#print'
  post '/print', to: 'orders#printi'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
    
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
    require 'socket'

    
    client = TCPSocket.new '192.168.1.33', 9100

    client.write "recep"
    client.write "\n\n\n\n\n\n\n\n"

    client.write "\x1D\x56\x01"
    client.close

  end

  def print
    puts "hello"
    kebab = params["anything"]["kebab"]
    poulet = params["anything"]["poulet"]
    cheese = params["anything"]["cheese"]
    saucisse = params["anything"]["saucisse"]
    steak = params["anything"]["a_steak"]
    steakp =params["anything"]["a_steak_poulet"]
    belge = params["anything"]["belge"]
    kofte = params["anything"]["kofte"]
    nugets = params["anything"]["nuggets"]
    patatos = params["anything"]["patatos"]
    pain = params["anything"]["pain"]
    durum = params["anything"]["durum"]
    assiete = params["anything"]["assiete"]
    salade = params["anything"]["salade"]
    tomate = params["anything"]["tomate"]
    oignon = params["anything"]["oignon"]
    rouge = params["anything"]["rouge"]

    blanche =params["anything"]["blanche"]
    ketchup = params["anything"]["ketchup"]
    mayonnaise = params["anything"]["mayonnaise"]
    samourai = params["anything"]["samourai"]
    harissa = params["anything"]["harissa"]
    curry = params["anything"]["Curry"]
    algérienne = params["anything"]["algérienne"]
    andalouse = params["anything"]["andalouse"]

    blanchef =params["anything"]["blanchef"]
    ketchupf = params["anything"]["ketchupf"]
    mayonnaisef = params["anything"]["mayonnaisef"]
    samouraif = params["anything"]["samouraif"]
    harissaf = params["anything"]["harissaf"]
    curryf = params["anything"]["Curryf"]
    algériennef = params["anything"]["algériennef"]
    andalousef = params["anything"]["andalousef"]


    frite = params["anything"]["frite"]
    gfrite = params["anything"]["g_frite"]
    boisson = params["anything"]["boisson"]
    @remarque =  params["anything"]["name"]
    desert = params["anything"]["desert"]
    etu = params["anything"]["etu"]
    petit = params["anything"]["p_bar"]
    grand = params["anything"]["g_bar"]

    if belge == "1"
      pain = "1"
    end
    # puts kebab 
    # puts poulet 
    # puts cheese 
    # puts saucisse 
    # puts steak 
    # puts steakp 
    # puts belge 
    # puts kofte 
    # puts nugets
    # puts pain
    # puts durum
    # puts assiete
    # puts salade
    # puts tomate
    # puts oignon
    # puts rouge
    # puts blanche
    # puts ketchup
    # puts mayonnaise
    # puts samourai
    # puts harissa
    # puts curry
    # puts algérienne
    # puts andalouse
    # puts frite
    # puts boisson
    
    viande = []

    if kebab == "1"
      viande << "kebab"
    end    

    if poulet == "1"
      viande << "poulet"
    end

    if cheese == "1"
      viande << "cheese"
    end

    if saucisse == "1"
      viande << "saucisse"
    end

    if steak == "1"
      viande << "american steak"
    end

    if steakp == "1"
      viande << "american poulet"
    end

    if belge == "1"
      viande << "belge"
    end

    if kofte == "1"
      viande << "kofte"
    end

    if nugets == "1"
      viande << "nugets"
    end

    type = []
    
    if pain == "1"
      type << "pain"
    end

    if durum == "1"
    type << "durum"
    end

    if assiete == "1"
    type << "assiete"
    end

    if petit == "1"
    type << "petite barquette"
    end

    if grand == "1"
    type << "grande barquette"
    end

    crud = []
    if salade == "1"
    crud << "salade"
    end

    if tomate == "1"
    crud << "tomate"
    end

    if oignon == "1"
    crud << "oignon"
    end

    if rouge == "1"
    crud << "chou rouge"
    end
 
    sauce = []

    if blanche == "1"
    sauce << "blanche"
    end

    if ketchup == "1"
    sauce << "ketchup"
    end

    if mayonnaise == "1"
    sauce << "mayonnaise"
    end

    if samourai == "1"
    sauce << "samourai"
    end

    if harissa == "1"
    sauce << "harissa"
    end

    if curry == "1"
    sauce << "curry"
    end

    if algérienne == "1"
    sauce << "algerienne"
    end

    if andalouse == "1"
    sauce << "andalouse"
    end

    saucef = []

    if blanchef == "1"
    saucef << "blanche"
    end

    if ketchupf == "1"
    saucef << "ketchup"
    end

    if mayonnaisef == "1"
    saucef << "mayonnaise"
    end

    if samouraif == "1"
    saucef << "samourai"
    end

    if harissaf == "1"
    saucef << "harissa"
    end

    if curryf == "1"
    saucef << "curry"
    end

    if algériennef == "1"
    saucef << "algerienne"
    end

    if andalousef == "1"
    saucef << "andalouse"
    end

    extra = []
    if frite == "1"
    extra << "frite"
    end

    if gfrite == "1"
    extra << "Grande frite"
    end

    if boisson == "1"
      extra << "boisson"
    end

    if desert == "1"
      extra << "desert"
    end


    @price = 0
    if viande.count != 1 && viande.count != 0 && assiete == "1"
      puts "menu spéeciale"
      @price += 13
      if boisson == "1"
        @price += 1
      end

    elsif assiete == "1" && viande.count == 1
      @price += 10
      if boisson == "1"
        @price += 1
      end

    elsif (durum == "1" || pain == "1" ) && belge == "0"
      @price += 5
      if frite == "1"
        if boisson == "0"
          @price += 1
        else
          @price += 2
        end
      elsif frite == "0" && boisson == "1"
        @price += 1.5
      end
    
    elsif belge == "1"
      @price = 3
      if frite == "1"
        if boisson == "0"
          @price += 1
        else
          @price += 2
        end
      elsif frite == "0" && boisson == "1"
        @price += 1.5
      
      end


    end

    if etu == "1"
      @price += -0.5
    end

    if gfrite == "1"
      @price += 2.5
    end

    if desert == "1"
      @price += 0.5
    end

    if petit == "1" && patatos == "1"
      @price += 3
    elsif grand == "1" && patatos == "1"
      @price += 4.5
    elsif petit == "1" && viande.count == 1 && patatos = "0" && nugets == "0"
      @price += 4
    elsif grand == "1" && viande.count == 1 && patatos = "0" && nugets == "0"
      @price += 5.5
    elsif petit == "1" && nugets == "1"
      @price += 4
    elsif grand == "1" && nugets == "1"
      @price += 5
    end

    if boisson == "1" && assiete == "0" && pain == "0" && durum == "0"
      @price += 1.5
    end

    if frite == "1" && assiete == "0" && pain == "0" && durum == "0"
      @price += 2
    end











    @lig1 = ""
    type.each do |f|
      @lig1 += f + " "
    end


    
    @lig2 = ""
    viande.each do |f|
      @lig2 += f + " "
    end



    @lig3 = ""
    crud.each do |f|
      @lig3 += f + " "
    end

    @lig4 = ""
    sauce.each do |f|
      @lig4 += f + " "
    end

    @lig6 = "Sauce frite: "
    saucef.each do |f|
      @lig6 += f + " "
    end

    @lig5 = ""
    extra.each do |f|
      @lig5 += f + " "
    end

    def printi
    client = TCPSocket.new '192.168.1.33', 9100

    client.write "\x1B\x21\x25"
    client.write "\n"
    client.write "#{@lig1}"
    client.write "\n"
    client.write @lig2
    client.write "\n"
    client.write @lig3
    client.write "\n"
    client.write @lig4
    client.write "\n"
    client.write @lig6
    client.write "\n"
    client.write @lig5
    client.write "\n"
    client.write @remarque
    client.write "\n\n\n\n\n\n"

    client.write "\x1D\x56\x01"
    client.close
  end



    

  end








  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.fetch(:order, {})
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<%= form_with(model: order, local: true) do |form| %>
  <% if order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<%= form_for :anything, url: "/print", method: :get do |f| %>

<div >
    
    <div class="midlle li">

        <div class= "kebab">
          <h4>Pain</h4>
          <%= f.check_box :pain, class: "bouton", checked: true %>
        </div>

        <div class= "kebab">
          <h4 class= "wr">durum</h4>
          <%= f.check_box :durum, class: "bouton" %>
        </div>
    
        <div class= "kebab">
          <h4>assiete</h4>
          <%= f.check_box :assiete, class: "bouton" %>
        </div>

        <div class= "kebab">
          <h4>P barque</h4>
          <%= f.check_box :p_bar, class: "bouton" %>
        </div>

        <div class= "kebab">
          <h4>G barque</h4>
          <%= f.check_box :g_bar, class: "bouton" %>
        </div>
        

        </div>
        <hr/>

    <!-- <h4>Viande</h4> -->
    <div class="midlle lv">

        <div class= "kebab">
          <h4>kebab</h4>
          <%= f.check_box :kebab, class: "bouton" %>
        </div>

        <div class= "kebab">
          <h4 class= "wr">poulet</h4>
          <%= f.check_box :poulet, class: "bouton" %>
        </div>
    
        <div class= "kebab">
          <h4>cheese</h4>
          <%= f.check_box :cheese, class: "bouton" %>
        </div>

   

        <div class= "kebab">
          <h4>saucisse</h4>
          <%= f.check_box :saucisse, class: "bouton" %>
        </div>

        
        <div class= "kebab">
          <h4>A steak</h4>
          <%= f.check_box :a_steak, class: "bouton" %>
        </div>

        </div>

        

        <div class="midlle lv">
      
        <div class= "kebab">
          <h4>A steak p</h4>
          <%= f.check_box :a_steak_poulet, class: "bouton" %>
        </div>

        
    
        <div class= "kebab">
          <h4>Belge</h4>
          <%= f.check_box :belge, class: "bouton" %>
        </div>

        <div class= "kebab">
          <h4>kofte</h4>
          <%= f.check_box :kofte, class: "bouton" %>
        </div>

        <div class= "kebab">
          <h4>Nuggets</h4>
          <%= f.check_box :nuggets, class: "bouton" %>
        </div>

        <div class= "kebab">
          <h4>Patatos</h4>
          <%= f.check_box :patatos, class: "bouton" %>
        </div>

      </div>


    </div>
    <hr/>

<!-- <h4>Type</h4> -->


        <!-- <h4>Crudité</h4> -->
    
    <div class="midlle lc">

        <div class= "kebab">
          <h4>Salade</h4>
          <%= f.check_box :salade, class: "bouton", checked: true %>
        </div>

        <div class= "kebab">
          <h4 class= "wr">tomate</h4>
          <%= f.check_box :tomate, class: "bouton", checked: true %>
        </div>
    
        <div class= "kebab">
          <h4>oignon</h4>
          <%= f.check_box :oignon, class: "bouton", checked: true %>
        </div>

        <div class= "kebab">
          <h4>chou rouge</h4>
          <%= f.check_box :rouge, class: "bouton" %>
        </div>

        </div>

  <hr/>
<!-- <h4>sauces</h4> -->
    <div class="midlle ls">

        <div class= "kebab">
          <h4>blanche</h4>
          <div class="midlle">
          <%= f.check_box :blanche, class: "bouton1" %>
          <%= f.check_box :blanchef, class: "bouton1" %>
        </div>
      </div>

        <div class= "kebab">
          <h4 class= "wr">ketchup</h4>
          <%#= f.check_box :ketchup, class: "bouton" %>
          <div class="midlle">
          <%= f.check_box :ketchup, class: "bouton1" %>
          <%= f.check_box :ketchupf, class: "bouton1" %>
        </div>
        </div>
    
        <div class= "kebab">
          <h4>mayonnaise</h4>
          <%#= f.check_box :mayonnaise, class: "bouton" %>
          <div class="midlle">
          <%= f.check_box :mayonnaise, class: "bouton1" %>
          <%= f.check_box :mayonnaisef, class: "bouton1" %>
        </div>
        </div>

        <div class= "kebab">
          <h4>samourai</h4>

          <%#= f.check_box :samourai, class: "bouton" %>
          <div class="midlle">
          <%= f.check_box :samourai, class: "bouton1" %>
          <%= f.check_box :samouraif, class: "bouton1" %>
        </div>
        </div>
        
        </div>
        <div class="midlle ls">

        <div class= "kebab">
          <h4 class= "wr">harissa</h4>
          <%#= f.check_box :harissa, class: "bouton" %>
          <div class="midlle">
          <%= f.check_box :harissa, class: "bouton1" %>
          <%= f.check_box :harissaf, class: "bouton1" %>
        </div>
        </div>
    
        <div class= "kebab">
          <h4>Curry</h4>
          <%#= f.check_box :Curry, class: "bouton" %>
          <div class="midlle">
          <%= f.check_box :Curry, class: "bouton1" %>
          <%= f.check_box :Curryf, class: "bouton1" %>
        </div>
        </div>

        <div class= "kebab">
          <h4>algérienne</h4>
          <%#= f.check_box :algérienne, class: "bouton" %>
          <div class="midlle">
          <%= f.check_box :algérienne, class: "bouton1" %>
          <%= f.check_box :algériennef, class: "bouton1" %>
        </div>
        </div>

        <div class= "kebab">
          <h4 class= "wr">andalouse</h4>
          <%#= f.check_box :andalouse, class: "bouton" %>
          <div class="midlle">
          <%= f.check_box :andalouse, class: "bouton1" %>
          <%= f.check_box :andalousef, class: "bouton1" %>
        </div>
        </div>
  
    </div>
    <hr/>
    
    <div class="midlle li">
    

    <div class= "kebab">
          <h4>frite</h4>
          <%= f.check_box :frite, class: "bouton" %>
        </div>
        
        

        <div class= "kebab">
          <h4 class= "wr">boisson</h4>
          <%= f.check_box :boisson, class: "bouton" %>
        </div>
        <div class= "kebab">
          <h4 class= "wr">etudiant</h4>
          <%= f.check_box :etu, class: "bouton" %>
        </div>

        <div class= "kebab">
          <h4>Gr frite</h4>
          <%= f.check_box :g_frite, class: "bouton" %>
        </div>

        <div class= "kebab">
          <h4 class= "wr">desert</h4>
          <%= f.check_box :desert, class: "bouton" %>
        </div>

        
    </div>
    <hr>

    <%= f.text_field :name, class: "form-control form-group mx-sm-3 mb-2", placeholder: "remarque" %>
    <hr>

<!-- <h4>menu</h4> -->


    <%= f.submit value="imprimer", class: "btn btn-primary btn-lg btn-block"%>
</div>

<% end %>


 

app/views/orders/new.html.erb
<h1>New Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Back', orders_path %>

app/views/orders/print.html.erb
<h1><%=  @price %>€</h1>


<hr>
<%= @lig1 %>
<%= @lig2 %>
<%= @lig3 %>
<%= @lig4 %>
<%= @lig6 %>
<%= @lig5 %>
<%= @remarque %>
<hr>

<%= form_for :anything, url: "/orders", method: :printi do |f| %>

 <%= button_to 'Invite a user', method: :printi  %>
 <% end %>

<%= link_to "Nouvelle commande", orders_path, class: "btn btn-primary btn-lg btn-block" %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>